---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes 

  - name: install apache2 package (u can write whatever)
    apt:
      name: apache2
      state: latest


  - name: instal php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
